name: Build and Deploy
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 코드 체크아웃
      uses: actions/checkout@v3

    - name: AWS 인증
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: ECR 로그인
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Docker 빌드 & ECR 푸시
      env:
        ECR_REGISTRY: 923516172483.dkr.ecr.ap-northeast-2.amazonaws.com
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/nestjs-app:$IMAGE_TAG .
        docker push $ECR_REGISTRY/nestjs-app:$IMAGE_TAG

    - name: k8s-gitops 레포 카나리 이미지 태그 업데이트
      env:
        IMAGE_TAG: ${{ github.sha }}
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: |
        git clone https://thsejrwn:$GIT_TOKEN@github.com/thsejrwn/k8s-gitops.git
        cd k8s-gitops

        # ✅ 신버전은 canary 에만 반영 (stable 은 건드리지 않음)
        sed -i "s|image:.*nestjs-app.*|image: 923516172483.dkr.ecr.ap-northeast-2.amazonaws.com/nestjs-app:$IMAGE_TAG|" 03-nestjs-canary.yaml

        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
        git add .
        git commit -m "canary: update image tag $IMAGE_TAG"
        git push
